### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by lixingguang** [Taming-the-BEAST/Skyline-plots#5]
I used the Birth Death Skyline Serial model, and could you please tell me what is this meaning: expression="becomeUninfectiousRate.t:hcv 1 samplingProportion.t:hcv - *
 and  I find that death rate = becomeUninfectiousRate - sampling rate, so how to get the sampling rate, thanks.

**Comment by laduplessis** [comment]
That is the expression for the death rate in Reverse Polish Notation (https://en.wikipedia.org/wiki/Reverse_Polish_notation), which is what RPNCalculator uses for mathematical expressions (nice and convenient because it's easy to parse and no parentheses are needed). 

You are right: 
death rate = becomeUninfectiousRate - samplingRate

But
samplingRate = becomeUninfectiousRate * samplingProportion

so
death rate = becomeUninfectiousRate (1 - samplingProportion)

Translate that to Reverse Polish Notation and you get:
becomeUninfectiousRate 1 samplingProportion - *

**Comment by lixingguang** [comment]
@laduplessis thanks for your reply. This is great!
